CREATE TABLE User (
	uid				BIGINT				NOT NULL PRIMARY KEY AUTO_INCREMENT,
	userId			VARCHAR(20)			NOT NULL,
	uPasswd			VARCHAR(16)			NOT NULL,
	uName			VARCHAR(20)			NOT NULL,
	uPhone			VARCHAR(13)			NOT NULL,
	uGrade			VARCHAR(10)			NOT NULL DEFAULT '방린이',
	uType			CHAR(1)				NOT NULL DEFAULT 'U',
	uCheck			BOOLEAN				NOT NULL DEFAULT '0',
	regDate			TIMESTAMP			NOT NULL DEFAULT	CURRENT_TIMESTAMP
)

CREATE TABLE Company (
	cid				BIGINT				NOT NULL PRIMARY KEY AUTO_INCREMENT,
	comId			VARCHAR(20)			NOT NULL,
	comPasswd		VARCHAR(16)			NOT NULL,
	comName			VARCHAR(20)			NOT NULL,
	comNum			VARCHAR(12)			NOT NULL,
	comAddress		VARCHAR(100)		NOT NULL,
	comTel			VARCHAR(13)			NOT NULL,
	comX			DOUBLE				NOT NULL,
	comY			DOUBLE				NOT NULL,
	regDate			TIMESTAMP			NOT NULL DEFAULT	CURRENT_TIMESTAMP
)

CREATE TABLE Theme (
	tid				BIGINT				NOT NULL PRIMARY KEY AUTO_INCREMENT,
	cid				BIGINT				NOT NULL,
	tName			VARCHAR(20)			NOT NULL,
	tCategory		VARCHAR(10)			NOT NULL,
	tLevel			INT					NOT NULL,
	tNum			INT					NOT NULL,
	tPrice			INT					NOT NULL,
	tDef			VARCHAR(500)		NOT NULL,
	tTime			INT					NOT NULL,
	tImage			VARCHAR(100)		NOT NULL,
	regDate			TIMESTAMP			NOT NULL DEFAULT	CURRENT_TIMESTAMP,
	CONSTRAINT Theme FOREIGN KEY (cid) REFERENCES Company(cid)
)

CREATE TABLE Reservation (
	rid				BIGINT				NOT NULL PRIMARY KEY AUTO_INCREMENT,
	uid				BIGINT				NOT NULL,
	tid				BIGINT				NOT NULL,
	rPrice			INT					NOT NULL,
	rDate			DATE				NOT NULL,
	rTime			TIME				NOT NULL,
	rNum			INT					NOT	NULL,
	regDate			TIMESTAMP			NOT NULL DEFAULT	CURRENT_TIMESTAMP,
	CONSTRAINT Reservation FOREIGN KEY (uid) REFERENCES User(uid), FOREIGN KEY (tid) REFERENCES theme(tid)
)

CREATE TABLE Board (
	bid				BIGINT				NOT NULL PRIMARY KEY AUTO_INCREMENT,
	uid				BIGINT				NOT NULL,
	bTitle			VARCHAR(100)		NOT NULL,
	bDef			VARCHAR(3000)		NOT NULL,
	bCategory		VARCHAR(10)			NOT NULL,
	regDate			TIMESTAMP			NOT NULL DEFAULT	CURRENT_TIMESTAMP,
	CONSTRAINT Board FOREIGN KEY (uid) REFERENCES User(uid)
)

CREATE TABLE BoardComment (
	bcid			BIGINT				NOT NULL PRIMARY KEY AUTO_INCREMENT,
	uid				BIGINT				NOT NULL,
	bid				BIGINT				NOT NULL,
	bcDef			VARCHAR(500)		NOT NULL,
	regDate			TIMESTAMP			NOT NULL DEFAULT	CURRENT_TIMESTAMP,
	CONSTRAINT BoardComment FOREIGN KEY (uid) REFERENCES User(uid), FOREIGN KEY (bid) REFERENCES Board(bid)
)

CREATE TABLE Question (
	qid				BIGINT				NOT NULL PRIMARY KEY AUTO_INCREMENT,
	uid				BIGINT				NOT NULL,
	cid				BIGINT				NOT NULL,
	qTitle			VARCHAR(100)		NOT NULL,
	qDef			VARCHAR(3000)		NOT NULL,
	regDate			TIMESTAMP			NOT NULL DEFAULT	CURRENT_TIMESTAMP,
	CONSTRAINT Question FOREIGN KEY (uid) REFERENCES User(uid), FOREIGN KEY (cid) REFERENCES Company(cid)
)

CREATE TABLE Answer (
	aid				BIGINT				NOT NULL PRIMARY KEY AUTO_INCREMENT,
	cid				BIGINT				NOT NULL,
	qid				BIGINT				NOT NULL,
	aDef			VARCHAR(1000)		NOT NULL,
	regDate			TIMESTAMP			NOT NULL DEFAULT	CURRENT_TIMESTAMP,
	CONSTRAINT Answer FOREIGN KEY (qid) REFERENCES Question(qid), FOREIGN KEY (cid) REFERENCES Company(cid)
)
